name: adaptive_scaffold
description: Widgets to easily build adaptive layouts, including navigation elements.
version: 0.4.6
repository: https://github.com/helpisdev/adaptive_scaffold.git
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  adaptive_scrollbar:
    git:
      url: https://github.com/helpisdev/adaptive-scrollbar.git
      ref: main
  collection: ^1.17.1
  flutter:
    sdk: flutter
  gtk_window:
    git:
      url: https://github.com/helpisdev/gtk_window.git
      ref: main
  stack: ^0.2.1
  utilities:
    git:
      url: https://github.com/helpisdev/utilities.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.0

dependency_overrides:
  collection: ^1.18.0
  handy_window: "^0.3.1"
  intl: ^0.18.1
