name: adaptive_scaffold
description: Widgets to easily build adaptive layouts, including navigation elements.
version: 0.4.9
repository: https://github.com/helpisdev/adaptive_scaffold.git
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  adaptive_scrollbar:
    path: packages/adaptive_scrollbar
  breakpoints_utilities:
    path: packages/gtk_window/packages/resizable_text/packages/breakpoints_utilities
  collection: ^1.17.1
  copy_with_extension: ^5.0.4
  flutter:
    sdk: flutter
  gtk_window:
    path: packages/gtk_window
  resizable_text:
    path: packages/gtk_window/packages/resizable_text

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  melos: ^3.1.0

dependency_overrides:
  collection: ^1.18.0
  handy_window: "^0.3.1"
  intl: ^0.18.1
